---
title: 
author: "Matt Parker"
date: "2023-10-26"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(rsample)     # data splitting 
library(dplyr)       # data wrangling
library(rpart)       # performing regression trees
library(rpart.plot)  # plotting regression trees
library(ipred)       # bagging
library(caret)       # bagging
library(glmnet)
library(readr)
library(psych)
library(tidyverse)
library(randomForest)
library(datasets)
library(e1071)
library(ranger) 
library(writexl)
library(mltools)
library(data.table)
library(car)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
```

## Response Variable Transformation

```{r}
forestfires <- read_csv("forestfires.csv")
par(mfrow=c(1,2))
hist(forestfires$area, main = "Burned Area", col = "red", xlab = "Burned Area")
forestfires$area <- log(forestfires$area + 1)
hist(forestfires$area, main = "Log Tranformed Burned Area", col = "orange", xlab = "Burned Area")
```

## Descriptive Statistics

```{r}
summary(forestfires)
df <- data.frame(describe(forestfires)[, -c(6, 7, 11, 12)])
View(df)
write_xlsx(df, "~/STAT 4893W/Forest.xlsx")
```

## Linear Regression

```{r}
forestfires$month <- as.factor(forestfires$month)
forestfires$day <- as.factor(forestfires$day)
new.forest <- one_hot(as.data.table(forestfires))

m1 <- lm(area ~ . - X - Y, data = new.forest)
step(m1, direction = "backward")
m2 <- lm(area ~ month_aug + month_dec + month_jul + month_jun + 
    month_mar + DMC + DC + temp + wind, data = new.forest)
summary(m1)
mean(m1$residuals^2)
summary(m2)
mean(m2$residuals^2)
```

## Regression Trees

```{r}
set.seed(123)

rt.1 <- rpart(formula = area ~ month_aug + month_dec + month_jul + month_jun + 
    month_mar + DMC + DC + temp + wind, data = new.forest, method = "anova", control = list(minsplit = 55, maxdepth = 13))

rt.2 <- rpart(formula = area ~ FFMC + DMC + DC + ISI, data = new.forest, method = "anova")

rt.3 <- rpart(formula = area ~ temp + RH + wind + rain, data = new.forest, method = "anova")

par(mfrow=c(1,3))
rpart.plot(rt.1, main = "Stepwise Tree")
rpart.plot(rt.2, main = "FWI Tree")
rpart.plot(rt.3, main = "Basic Weather Tree")
```

## Random Forest

```{r}
set.seed(123)
fire <- sample(2, nrow(new.forest), replace = TRUE, prob = c(0.7, 0.3))
train <- new.forest[fire==1,]
test <- new.forest[fire==2,]

rf <- randomForest(area ~ month_aug + month_dec + month_jul + month_jun + 
    month_mar + DMC + DC + temp + wind, data = train, type = "regression", keep.forest = FALSE, importance = TRUE, mtry = 2) 
print(rf)
plot(rf)
which.min(rf$mse)
sqrt(rf$mse[which.min(rf$mse)])
varImpPlot(rf, main = "Variable Importance Plot", pch = 18)
```



